use_frameworks!

target 'SwiftCronExample' do
pod 'SwiftCron', :path => '../'
end

target 'SwiftCronExampleTests' do
pod 'SwiftCron', :path => '../'
pod 'SwiftLint'
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
